export enum AccountStatus {
  DRAFT = 'DRAFT',
  EMAIL_PENDING = 'EMAIL_PENDING',
  PROFILE_INCOMPLETE = 'PROFILE_INCOMPLETE',
  DOCS_PENDING = 'DOCS_PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ACTIVE = 'ACTIVE',
  UPGRADE_PENDING = 'UPGRADE_PENDING',
  COMPANY_CHANGE = 'COMPANY_CHANGE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
  DEACTIVATED = 'DEACTIVATED',
  BANNED = 'BANNED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum UserRole {
  RIDE_GIVER = 'RIDE_GIVER',
  RIDE_SEEKER = 'RIDE_SEEKER',
  BOTH = 'BOTH',
  ADMIN = 'ADMIN',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum EcoLevel {
  SEED = 'SEED',
  SPROUT = 'SPROUT',
  LEAF = 'LEAF',
  TREE = 'TREE',
  FOREST = 'FOREST',
}

export enum RideStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum RequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  HOLD = 'HOLD',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum NotificationType {
  RIDE_APPROVED = 'RIDE_APPROVED',
  RIDE_REJECTED = 'RIDE_REJECTED',
  RIDE_CONFIRMED = 'RIDE_CONFIRMED',
  RIDE_STARTED = 'RIDE_STARTED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  RIDE_CANCELLED = 'RIDE_CANCELLED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  HOLD_EXPIRING = 'HOLD_EXPIRING',
  HOLD_EXPIRED = 'HOLD_EXPIRED',
  VERIFICATION_APPROVED = 'VERIFICATION_APPROVED',
  VERIFICATION_REJECTED = 'VERIFICATION_REJECTED',
  SEEKER_BOARDED = 'SEEKER_BOARDED',
  SEEKER_DEBOARDED = 'SEEKER_DEBOARDED',
  SEEKER_NO_SHOW = 'SEEKER_NO_SHOW',
  SOS_ALERT = 'SOS_ALERT',
  GENERIC = 'GENERIC',
}

export enum BoardingStatus {
  WAITING = 'WAITING',
  BOARDED = 'BOARDED',
  DEBOARDED = 'DEBOARDED',
  NO_SHOW = 'NO_SHOW',
}

export enum WsEvents {
  GPS_UPDATE = 'gps:update',
  RIDE_STATUS = 'ride:status',
  NOTIFICATION_NEW = 'notification:new',
  SOS_ALERT = 'sos:alert',
  JOIN_RIDE = 'ride:join',
  LEAVE_RIDE = 'ride:leave',
}
