[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd ../.. && npm ci"]

[phases.build]
cmds = [
  "cd ../.. && npm run build --workspace=packages/shared",
  "npm run build"
]

[start]
cmd = "npx prisma db push --schema=../../prisma/schema.prisma --accept-data-loss && node dist/main"
