[options]
installCmd = "cd ../.. && npm ci && cd apps/api"
buildCmd = "cd ../.. && npm run build --workspace=packages/shared && cd apps/api && npx nest build"
startCmd = "npx prisma generate --schema=../../prisma/schema.prisma && npx prisma db push --schema=../../prisma/schema.prisma --accept-data-loss && node dist/main"
